<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Multiupdater</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx" />
    <Reference Include="KrokoshaCasualtiesMP" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Unity.VisualScripting.Core" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.IMGUIModule" />
  </ItemGroup>
</Project>
