<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KrokoshaCasualtiesMP</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx" />
    <Reference Include="DiscordRPC" />
    <Reference Include="LiteNetLib" />
    <Reference Include="Mono.Security" />
    <Reference Include="MonoMod.Utils" />
    <Reference Include="Multiupdater" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="OpusSharp.Core" />
    <Reference Include="Steamworks.NET" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Unity.Burst" />
    <Reference Include="Unity.RenderPipelines.Core.Runtime" />
    <Reference Include="Unity.RenderPipelines.Universal.Runtime" />
    <Reference Include="Unity.TextMeshPro" />
    <Reference Include="Unity.VisualScripting.Core" />
    <Reference Include="UnityEngine.AnimationModule" />
    <Reference Include="UnityEngine.AssetBundleModule" />
    <Reference Include="UnityEngine.AudioModule" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.GridModule" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="UnityEngine.ImageConversionModule" />
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="UnityEngine.ParticleSystemModule" />
    <Reference Include="UnityEngine.Physics2DModule" />
    <Reference Include="UnityEngine.ScreenCaptureModule" />
    <Reference Include="UnityEngine.TextRenderingModule" />
    <Reference Include="UnityEngine.TilemapModule" />
    <Reference Include="UnityEngine.UI" />
    <Reference Include="UnityEngine.UIModule" />
    <Reference Include="UnityEngine.UnityWebRequestModule" />
  </ItemGroup>
</Project>
